services:
  - type: web
    name: farmly-rag-service
    env: python
    rootDirectory: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn rag_service:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: QDRANT_URL
        sync: false
      - key: QDRANT_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: PORT
        value: 10000
